//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int KitapId { get; set; }
        public string KitapAdi { get; set; }
        public string KitapKonusu { get; set; }
        public string Yayinevi { get; set; }
        public string YayinTarihi { get; set; }
        public Nullable<int> YazarId { get; set; }
    
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
